import LoginAppLogo from "../assets/images/high5-std.svg";
import loginImg from "../assets/images/loginimg.png";
// import LoginSideimage from "../assets/images/tribal-block.svg";
// import PageNotFoundImage from "../assets/images/high5-std.svg";
// import LoaderImg from "../assets/images/loader.gif";
import SetPasswordSideImage from "../assets/images/tribalpattern-key.svg";
// import ButtonLoader from "../assets/images/button-loader.gif";
// import ButtonWhiteLoader from "../assets/images/button-loader-white.gif";
import SidebarLogo from "../assets/images/high5-mark-circle.svg";
// import LogoMark from "../assets/images/logo-blue-whitemark.svg";
// import High5DarkIcon from "../assets/images/high5-mark-circle-dark.svg";
// import TenantImage from "../assets/images/tanent-img-placeholder.png";

export { LoginAppLogo, SidebarLogo, SetPasswordSideImage, loginImg };

export const apiDomain = "https://high5vetdev.azurewebsites.net";
//export const apiDomain = "https://high5vettingqa-api.azurewebsites.net";
// export const apiDomain = "http://localhost:8080";

// export const FE_URL = "http://localhost:3000"; // LOCAL
export const FE_URL = "https://vetdev.high5hire.com"; // DEV
// export const FE_URL = "https://vetqa.high5hire.app";   // QA
// export const FE_URL = "https://vetqa.high5hire.app";   // DEMO
// export const FE_URL = "https://vetqa.high5hire.app";   // PROD

export const categoryData = [
  { SourceName: "MCQ", value: "MCQ" },
  { SourceName: "OneWay", value: "OneWay" },
  { SourceName: "General", value: "General" },
];

export const expiryData = [
  { SourceName: "1 day", value: 1 },
  { SourceName: "2 days", value: 2 },
  { SourceName: "3 days", value: 3 },
  { SourceName: "4 days", value: 4 },
  { SourceName: "5 days", value: 5 },
  { SourceName: "1 week", value: 7 },
  { SourceName: "2 weeks", value: 14 },
  { SourceName: "3 weeks", value: 21 },
  { SourceName: "1 month", value: 30 },
];
export const SKILLS = [
  "AJAX",
  "AML",
  "ASP.NET",
  "AWS",
  "Azure",
  "C++",
  "Certified Ethical Hacker (CEH)",
  "Cisco CCNA",
  "CISSP",
  "CompTIA Security+.",
  "CSS",
  "data mining and modeling",
  "database management",
  "Django",
  "Docker",
  "ETAP",
  "Golang",
  "Google Cloud ML Engine",
  "Java",
  "JavaScript",
  "Joomla",
  "Linux",
  "macOS",
  "MATLAB",
  "Microsoft Hyper-V",
  "Multisim",
  "Node.js",
  "Objective-C",
  "OpenCart",
  "Oracle VM VirtualBox",
  "PHP",
  "PrestaShop",
  "Pspice",
  "Python",
  "QEMU",
  "ReactJS",
  "Ruby",
  "scikit-learn",
  "Shopify.",
  "Simulink",
  "Verilog",
  "WooCommerce",
  "XEN.",
  "12-Lead ECG Interpretation and Placements",
  "4D (4th Dimension)",
  "A/B Testing",
  "Acrobat",
  "ADABAS",
  "Agile",
  "Altibase",
  "AmazonRDS",
  "Angular",
  "ASP",
  "AutoCAD",
  "Automation",
  "Backbone.js",
  "Basic Statistics",
  "Bootstrap",
  "Budgeting",
  "Business Process Management",
  "Closing Sales",
  "Cloudera",
  "CMS Tools",
  "Coding",
  "Compliance",
  "Corel Draw",
  "Cost Management",
  "Couchbase",
  "CouchDB",
  "CRO/CRM",
  "Customer Needs Analysis",
  "Data Structures",
  "DbVisualizer",
  "Delphi",
  "Email Marketing",
  "Ember.js",
  "ES5",
  "Express.js",
  "FileMaker",
  "Firebase",
  "Free Hand",
  "G-Tube Feedings and Care",
  "General Marketing Skills",
  "Ghostwriting",
  "Glucose Checks",
  "GO",
  "Grant Writing",
  "GraphQL",
  "Groovy",
  "Grunt",
  "Gulp",
  "Hadoop HDFS",
  "Haskell",
  "HTML",
  "HTML DOM",
  "HTML/CSS",
  "HTML5",
  "IBM DB2",
  "Illustrator",
  "InDesign",
  "Informix",
  "Informix Dynamic Server",
  "Journalism",
  "jQuery",
  "JSON",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Layout",
  "Lead Qualification",
  "Less",
  "Lua",
  "Machine Learning",
  "Magento",
  "ManageEngine Applications Manager",
  "MariaDB",
  "Meteor.js",
  "Microsoft Access",
  "Microsoft SQL Server",
  "Microsoft Windows",
  "MongoDB",
  "Monitoring Vital Signs",
  "MySQL",
  "Neo4j",
  "NIH Stroke Scale Patient Assessment",
  "Objection Handling",
  "Open Source Experience",
  "Oracle RDBMS",
  "OrientDB",
  "OSCP",
  "PaaS (Azure and Heroku)",
  "Parse.com",
  "Patient Transport",
  "Perl",
  "Phlebotomy",
  "Photoshop",
  "PHP",
  "phpMyAdmin",
  "Planning",
  "PostgresSQL",
  "PowerShell",
  "PPC",
  "Presentation",
  "Product Demo",
  "Product Knowledge",
  "Project Evaluation",
  "Project Management",
  "Prospecting",
  "Record Keeping",
  "Redis",
  "Redux",
  "Rehabilitation Therapy",
  "Relationship Building",
  "REST",
  "Risk Management",
  "Robomongo",
  "Rust",
  "SAP Sybase ASE",
  "Sass",
  "Scala",
  "Scientific Writing",
  "Scrum",
  "Security",
  "SEO",
  "Seqel PRO",
  "Shell",
  "Sketching",
  "Social Media",
  "SolarWinds Database Performance Analyzer",
  "SQL",
  "SQL Developer",
  "SQLite",
  "Staffing",
  "Statistical analysis",
  "Storybook",
  "Technical Reports",
  "Technical Writing",
  "TensorFlow",
  "Teradata",
  "Toad",
  "TypeScript",
  "Typography",
  "Urgent Care/Emergency Care",
  "UX Design",
  "Visual Basic .NET",
  "VMware vSphere",
  "W3.CSS",
  "Web Development",
  "WordPress",
  "Work Scheduling",
  "Wound Care and Dressing",
  "XML",
  "Yoast",
];
