export const oneWayTestData = {
  companyInfo: {
    companyName: "NA",
    companyLogo: "NA",
  },
  createdBy: {
    id: "62f20198d4d1c1f16799d2e8",
    name: "Monisha",
    role: "user",
  },
  modifiedBy: {
    id: "62f20198d4d1c1f16799d2e8",
    name: "Monisha",
    role: "user",
  },
  startTest: {
    takes: 0,
  },
  _id: "62f203e6d4d1c1f16799d331",
  name: "Mark",
  email: "mark@yopmail.com",
  testAssign: {
    createdBy: {
      id: "62f20198d4d1c1f16799d2e8",
      name: "Monisha",
      role: "user",
    },
    modifiedBy: {
      id: "62f20198d4d1c1f16799d2e8",
      name: "Monisha",
      role: "user",
    },
    _id: "62f203bed4d1c1f16799d323",
    testName: "Practice Assessment",
    role: "Software Engineer",
    skills: ["English", "Science"],
    testCategory: "MCQ",
    questions: [
      {
        question:
          "Which will be a suitable answer concerning the bold word in a given sentence? If I am present there now, I would help him.",
        options: ["I was", "I were", "I have been", "No improvement"],
        answer: ["I were"],
        tag: [],
        remark: "",
        type: "MCQ",
        skill: "Redux",
        difficulty: "Simple",
        takes: "",
        duration: "30",
        createdBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        modifiedBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        imageUrl: "",
        deleted: false,
        _id: "62f203b8d4d1c1f16799d31s",
        createdAt: "2022-08-09T06:50:32.564Z",
        updatedAt: "2022-08-09T06:50:32.564Z",
        __v: 0,
      },
      {
        question:
          "In the following sentence, a word or phrase is written in bold. Choose the word nearest in meaning to the bold part.  He is a good-looking but insipid young man.",
        options: ["Arrogant", "Unscrupulous", "Sick", "Lacking in spirit"],
        answer: ["Lacking in spirit"],
        tag: [],
        remark: "Web development",
        type: "MCQ",
        skill: "Redux",
        difficulty: "Simple",
        takes: "",
        duration: "15",
        createdBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        modifiedBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        imageUrl: "",
        deleted: false,
        _id: "62f20294d4d1c1f16799d314",
        createdAt: "2022-08-09T06:45:40.845Z",
        updatedAt: "2022-08-09T06:45:40.845Z",
        __v: 0,
      },
    ],
    reviewer: {
      reviewerEmail: "",
      instructions: "",
    },
    details: {
      duration: "15",
    },
    invited: false,
    expired: "7",
    deleted: false,
    createdAt: "2022-08-09T06:50:38.026Z",
    updatedAt: "2022-08-09T06:50:38.026Z",
    __v: 0,
  },
  uniqueCode: "MTY9B5",
  testCompleted: false,
  testInvited: false,
  expiryDays: 7,
  takesForTest: 2,
  deleted: false,
  createdAt: "2022-08-09T06:51:18.018Z",
  updatedAt: "2022-08-16T13:17:20.876Z",
  __v: 0,
};

export const generalTestData = {
  companyInfo: {
    companyName: "NA",
    companyLogo: "NA",
  },
  createdBy: {
    id: "62f20198d4d1c1f16799d2e8",
    name: "Monisha",
    role: "user",
  },
  modifiedBy: {
    id: "62f20198d4d1c1f16799d2e8",
    name: "Monisha",
    role: "user",
  },
  startTest: {
    takes: 0,
  },
  _id: "62f203e6d4d1c1f16799d331",
  name: "Mark",
  email: "mark@yopmail.com",
  testAssign: {
    createdBy: {
      id: "62f20198d4d1c1f16799d2e8",
      name: "Monisha",
      role: "user",
    },
    modifiedBy: {
      id: "62f20198d4d1c1f16799d2e8",
      name: "Monisha",
      role: "user",
    },
    _id: "62f203bed4d1c1f16799d323",
    testName: "Practice Assessment",
    role: "Content Writer",
    skills: ["Engilsh", "Science"],
    testCategory: "MCQ",
    questions: [
      // {
      //   createdBy: {
      //     id: "6305fd4e3cdfe1421c1c76e0",
      //     firstName: "Super",
      //     lastName: "Admin",
      //     role: "admin",
      //     companyId: "",
      //     projectId: "",
      //   },
      //   modifiedBy: {
      //     id: "6305fd4e3cdfe1421c1c76e0",
      //     firstName: "Super",
      //     lastName: "Admin",
      //     role: "admin",
      //     companyId: "",
      //     projectId: "",
      //   },
      //   _id: "6343f8ff68fddc5b46c249ef",
      //   question: "What do you mean by 'Volition?'",
      //   options: [],
      //   answer: [
      //     "Volition is a noun word which means the power of using will or choice.",
      //   ],
      //   tag: [],
      //   remark: "",
      //   type: "OneWay",
      //   skill: "ReactJS",
      //   difficulty: "Simple",
      //   takes: "1",
      //   duration: "10",
      //   marks: null,
      //   imageUrl: "",
      //   deleted: false,
      //   createdAt: "2022-10-10T10:50:39.343Z",
      //   updatedAt: "2022-10-10T10:50:39.343Z",
      //   __v: 0,
      // },
      // {
      //   createdBy: {
      //     id: "6305fd4e3cdfe1421c1c76e0",
      //     firstName: "Super",
      //     lastName: "Admin",
      //     role: "admin",
      //     companyId: "",
      //     projectId: "",
      //   },
      //   modifiedBy: {
      //     id: "6305fd4e3cdfe1421c1c76e0",
      //     firstName: "Super",
      //     lastName: "Admin",
      //     role: "admin",
      //     companyId: "",
      //     projectId: "",
      //   },
      //   _id: "6343f8ff68fddc5b46c249ef",
      //   question: "Refer to a term for an event Happening in two years.",
      //   options: [],
      //   answer: ["Biennial"],
      //   tag: [],
      //   remark: "",
      //   type: "OneWay",
      //   skill: "ReactJS",
      //   difficulty: "Simple",
      //   takes: "1",
      //   duration: "10",
      //   marks: null,
      //   imageUrl: "",
      //   deleted: false,
      //   createdAt: "2022-10-10T10:50:39.343Z",
      //   updatedAt: "2022-10-10T10:50:39.343Z",
      //   __v: 0,
      // },
      {
        createdBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        modifiedBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        _id: "6343f8ff68fddc5b46c249df",
        question: "What do you mean by the idiom Lost in the clouds?",
        options: [],
        answer: ["Confused"],
        tag: [],
        remark: "",
        type: "OneWay",
        skill: "ReactJS",
        difficulty: "Simple",
        takes: "1",
        duration: "10",
        marks: null,
        imageUrl: "",
        deleted: false,
        createdAt: "2022-10-10T10:50:39.343Z",
        updatedAt: "2022-10-10T10:50:39.343Z",
        __v: 0,
      },
      {
        createdBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        modifiedBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        _id: "6343f8ff68fddc5b46c249df",
        question:
          "In a certain code, 'SOBER' is written as 'RNADQ.' How can 'LOTUS' be written in that code?",
        options: [],
        answer: ["KNSTR"],
        tag: [],
        remark: "",
        type: "OneWay",
        skill: "ReactJS",
        difficulty: "Simple",
        takes: "1",
        duration: "10",
        marks: null,
        imageUrl: "",
        deleted: false,
        createdAt: "2022-10-10T10:50:39.343Z",
        updatedAt: "2022-10-10T10:50:39.343Z",
        __v: 0,
      },
      {
        createdBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        modifiedBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        _id: "6343f8ff68fddc5b46c249eb",
        question: "Describe a Supercomputer.",
        options: ["Gases", "Liquids", "Solids", "None of the above"],
        answer: ["Gases"],
        tag: [],
        remark: "",
        type: "Multiline",
        skill: "ReactJS",
        difficulty: "Simple",
        takes: "1",
        duration: "10",
        marks: null,
        imageUrl: "",
        deleted: false,
        createdAt: "2022-10-10T10:50:39.343Z",
        updatedAt: "2022-10-10T10:50:39.343Z",
        __v: 0,
      },
      {
        createdBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        modifiedBy: {
          id: "6305fd4e3cdfe1421c1c76e0",
          firstName: "Super",
          lastName: "Admin",
          role: "admin",
          companyId: "",
          projectId: "",
        },
        _id: "6343f8ff68fddc5b46c249eb",
        question: "What do you understand about economic planning?",
        options: [],
        answer: [
          "Economic planning is the process in which the limited natural resources are used skillfully so as to achieve the desired goals.",
        ],
        tag: [],
        remark: "",
        type: "Multiline",
        skill: "ReactJS",
        difficulty: "Simple",
        takes: "1",
        duration: "10",
        marks: null,
        imageUrl: "",
        deleted: false,
        createdAt: "2022-10-10T10:50:39.343Z",
        updatedAt: "2022-10-10T10:50:39.343Z",
        __v: 0,
      },
      {
        question:
          "Which will be a suitable answer concerning the bold word in a given sentence? If I am present there now, I would help him.",
        options: ["I was", "I were", "I have been", "No improvement"],
        answer: ["I were"],
        tag: [],
        remark: "",
        type: "MCQ",
        skill: "Redux",
        difficulty: "Simple",
        takes: "",
        duration: "30",
        createdBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        modifiedBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        imageUrl: "",
        deleted: false,
        _id: "62f203b8d4d1c1f16799d31s",
        createdAt: "2022-08-09T06:50:32.564Z",
        updatedAt: "2022-08-09T06:50:32.564Z",
        __v: 0,
      },
      {
        question:
          "In the following sentence, a word or phrase is written in bold. Choose the word nearest in meaning to the bold part.  He is a good-looking but insipid young man.",
        options: ["Arrogant", "Unscrupulous", "Sick", "Lacking in spirit"],
        answer: ["Lacking in spirit"],
        tag: [],
        remark: "Web development",
        type: "MCQ",
        skill: "Redux",
        difficulty: "Simple",
        takes: "",
        duration: "15",
        createdBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        modifiedBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        imageUrl: "",
        deleted: false,
        _id: "62f20294d4d1c1f16799d314",
        createdAt: "2022-08-09T06:45:40.845Z",
        updatedAt: "2022-08-09T06:45:40.845Z",
        __v: 0,
      },
    ],
    reviewer: {
      reviewerEmail: "",
      instructions: "",
    },
    details: {
      duration: "15",
    },
    invited: false,
    expired: "7",
    deleted: false,
    createdAt: "2022-08-09T06:50:38.026Z",
    updatedAt: "2022-08-09T06:50:38.026Z",
    __v: 0,
  },
  uniqueCode: "MTY9B5",
  testCompleted: false,
  testInvited: false,
  expiryDays: 7,
  takesForTest: 2,
  deleted: false,
  createdAt: "2022-08-09T06:51:18.018Z",
  updatedAt: "2022-08-16T13:17:20.876Z",
  __v: 0,
};

export const mcqTestData = {
  companyInfo: {
    companyName: "NA",
    companyLogo: "NA",
  },
  createdBy: {
    id: "62f20198d4d1c1f16799d2e8",
    name: "Monisha",
    role: "user",
  },
  modifiedBy: {
    id: "62f20198d4d1c1f16799d2e8",
    name: "Monisha",
    role: "user",
  },
  startTest: {
    takes: 0,
  },
  _id: "62f203e6d4d1c1f16799d331",
  name: "Mark",
  email: "mark@yopmail.com",
  testAssign: {
    createdBy: {
      id: "62f20198d4d1c1f16799d2e8",
      name: "Monisha",
      role: "user",
    },
    modifiedBy: {
      id: "62f20198d4d1c1f16799d2e8",
      name: "Monisha",
      role: "user",
    },
    _id: "62f203bed4d1c1f16799d323",
    testName: "Practice Assessment",
    role: "Software Engineer",
    skills: ["English", "Science"],
    testCategory: "MCQ",
    questions: [
      {
        question:
          "Which will be a suitable answer concerning the bold word in a given sentence? If I am present there now, I would help him.",
        options: ["I was", "I were", "I have been", "No improvement"],
        answer: ["I were"],
        tag: [],
        remark: "",
        type: "MCQ",
        skill: "Redux",
        difficulty: "Simple",
        takes: "",
        duration: "30",
        createdBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        modifiedBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        imageUrl: "",
        deleted: false,
        _id: "62f203b8d4d1c1f16799d31s",
        createdAt: "2022-08-09T06:50:32.564Z",
        updatedAt: "2022-08-09T06:50:32.564Z",
        __v: 0,
      },
      {
        question:
          "In the following sentence, a word or phrase is written in bold. Choose the word nearest in meaning to the bold part.  He is a good-looking but insipid young man.",
        options: ["Arrogant", "Unscrupulous", "Sick", "Lacking in spirit"],
        answer: ["Lacking in spirit"],
        tag: [],
        remark: "Web development",
        type: "MCQ",
        skill: "Redux",
        difficulty: "Simple",
        takes: "",
        duration: "15",
        createdBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        modifiedBy: {
          id: "62f20198d4d1c1f16799d2e8",
          name: "Monisha",
          role: "user",
        },
        imageUrl: "",
        deleted: false,
        _id: "62f20294d4d1c1f16799d314",
        createdAt: "2022-08-09T06:45:40.845Z",
        updatedAt: "2022-08-09T06:45:40.845Z",
        __v: 0,
      },
    ],
    reviewer: {
      reviewerEmail: "",
      instructions: "",
    },
    details: {
      duration: "15",
    },
    invited: false,
    expired: "7",
    deleted: false,
    createdAt: "2022-08-09T06:50:38.026Z",
    updatedAt: "2022-08-09T06:50:38.026Z",
    __v: 0,
  },
  uniqueCode: "MTY9B5",
  testCompleted: false,
  testInvited: false,
  expiryDays: 7,
  takesForTest: 2,
  deleted: false,
  createdAt: "2022-08-09T06:51:18.018Z",
  updatedAt: "2022-08-16T13:17:20.876Z",
  __v: 0,
};
